# fly.toml app configuration file generated for cold-wind-8148 on 2023-09-06T17:01:34+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cold-wind-8148"
primary_region = "nrt"

[build]

[[services]]
  protocol = "tcp"
  internal_port = 23

  [[services.ports]]
    port = 23
