# fly.toml app configuration file generated for cold-wind-8148 on 2023-09-06T16:26:06+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cold-wind-8148"
primary_region = "nrt"

[build]

[http_service]
internal_port = 23
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]
