# fly.toml app configuration file generated for lingering-fire-5727 on 2023-12-29T21:19:06+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lingering-fire-5727"
primary_region = "nrt"

[build]

[[services]]
  protocol = "tcp"
  internal_port = 23

  [[services.ports]]
    port = 23
